version: "3.6"

services:
  httpbin-service:
    image: docker.io/mccutchen/go-httpbin:latest
    ports:
      - "8080"
    deploy :
      mode : replicated
      replicas : 2
      resources :
        limits :
          cpus : "2.0"
          memory : "200M"
        reservations :
          cpus : "1.0"
          memory : "100M"
#    networks :
#      - load-balancer

  webapp-service:
    image: webapp-service:v1
    environment:
      - APP_ARGS=--spring.profiles.active=dev --spring.threads.virtual.enabled=false --http-bin.server.url=http://api-gateway:8000/httpbin
    # - JAVA_OPTS=-Xmx1g
    # To externalize the configurations:
    # Pass the config-location to APP_ARGS as follows:-
    #  - APP_ARGS=--spring.config.location=/opt/webapp/conf/application.properties OR --spring.config.additional-location=/opt/webapp/conf/application.properties
    # Mount a volume with your path-to-application.properties file location
    # volumes:
    #   - <path-to-application.properties-file>:/opt/webapp/conf:ro
    ports:
      - "8090"
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "2.0"
          memory: "200M"
        reservations:
          cpus: "1.0"
          memory: "100M"
    depends_on:
      httpbin-service:
        condition: service_started
#    networks :
#      - load-balancer

  api-gateway:
    image: nginx-service:v1
    container_name: nginx-api-gateway
    ports:
      - "8000:8000"
#    volumes:
#     - <path-to-nginx.conf>:/etc/nginx/nginx.conf:ro
    depends_on:
      webapp-service:
        condition: service_started
      httpbin-service :
        condition : service_started
#    networks:
#      - load-balancer

networks:
#  load-balancer:
  default:
    driver: bridge
    name : dev-network
