## spring configs
server.port=8090
spring.application.name=webapp
server.servlet.context-path=/${spring.application.name}
spring.threads.virtual.enabled=false

## spring-actuator config
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=env
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

## application server configs
http-bin.server.url=http://localhost:8080

## logging configs
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.webapp.config.AppFilterLogger=DEBUG
logging.level.com.webapp.config.RestClientInterceptor=DEBUG
logging.level.com.webapp.config.AppWebClientInterceptor=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [${spring.application.name}] [%thread] [%X{traceId:-}:%X{spanId:-}] %-5level %logger{36} - %msg%n
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]

## App-filter logging config
# Enable/disable client logging (Even enabled, set logging level to DEBUG to see the logs)
app.filter.enabled=true
app.filter.include-request-headers=true
app.filter.include-request-body=true
app.filter.include-response-headers=true
app.filter.include-response-body=true
app.filter.max-body-length=100000

## client logging configs
# Enable/disable client logging (Even enabled, set logging level to DEBUG to see the logs)
client.logging.enabled=true
client.logging.include-request-headers=true
client.logging.include-request-body=true
client.logging.include-response-headers=true
client.logging.include-response-body=true
# Max length of request/response body to log. If body length exceeds this value, it will be truncated.
client.logging.max-body-length=10000

## Enable Zipkin tracing
management.tracing.sampling.probability=1.0
## Need to have a zipkin server running at this endpoint: docker run --rm -it -p 9411:9411 openzipkin/zipkin:latest
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.zipkin.tracing.connect-timeout=5s
management.zipkin.tracing.read-timeout=10s
## Enable context propagation for Reactor (WebFlux)
spring.reactor.context-propagation=auto
